ci: add config_h_verify job
Add a dedicated CI job to avoid accidental issues while converting the
plain Makefile-based configuration to Kconfig. The job ensures that
the resulting 'conf.h' stays the same while moving the configuration
from make variables to Kconfig.

The reference must be updated if the default value changes for a
certain platform.

Signed-off-by: Marco Felsch <m.felsch@pengutronix.de>

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -375,6 +375,57 @@ jobs:
           ccache -s -v
           eval "$MAKE_COMMANDS"
           ccache -s -v
+  config_h_verify:
+    name: Kconfig verify (all platforms)
+    runs-on: ubuntu-latest
+    container: jforissier/optee_os_ci
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v4
+      - name: Update Git config
+        run: git config --global --add safe.directory ${GITHUB_WORKSPACE}
+
+      - name: Verify conf.h for all platforms
+        shell: bash
+        run: |
+          set -e
+
+          testdir="tests/config-header-test"
+          reference_confh_dir="$testdir/config-header-references"
+          outdir="ci-confh-test"
+
+          # Generate the conf.h and compare them against the current reference
+          "$testdir"/gen-references --outdir "$outdir"
+
+          reference_configs="$(ls -1 $reference_confh_dir | wc -l)"
+          new_configs="$(ls -1 $outdir | wc -l)"
+
+          if "$reference_configs" != "$new_configs"; then
+            echo "FAIL: num of references configs $reference_configs != $new_configs"
+            exit 1
+          fi
+
+          for conf_h in ls -1 $outdir/*.conf.h; do
+            refconf_h = "$reference_confh_dir"/"$(basename $conf_h)"
+
+            if ! diff -u "$refconf_h" "$conf_h" >> kconfig-verify.diff; then
+              echo "FAIL: $platform"
+              exit 1
+            else
+              echo "OK:   $platform"
+            fi
+          done
+
+          exit 0
+
+      - name: Upload combined diff on failure
+        if: failure()
+        uses: actions/upload-artifact@v4
+        with:
+          name: kconfig-verify-diffs
+          path: kconfig-verify.diff
+          retention-days: 14
+
   QEMUv7_checks_image_build:
     name: Build QEMUv7 image
     runs-on: ubuntu-latest
